server:
  port: 8080

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: '*'
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      routes:
        - id: gestion-entradas-service
          uri: http://localhost:8082/  # Ruta directa al servicio de gestion de entradas
          predicates:
            - Path=/entrada/**
        - id: gestion-salidas-service
          uri: http://localhost:8083/  # Ruta directa al servicio de gestion de salidas
          predicates:
            - Path=/salidas/**
        - id: resumen-service
          uri: http://localhost:8084/  # Ruta directa al servicio de resumen
          predicates:
            - Path=/resumen/**
