server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/schnjov/POR_Tingeso.git
          search-paths: config-service/src/main/resources/config-data
  application:
    name: config-service